# Generated by Django 5.1.7 on 2025-03-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_farmer_name_farmtype_farm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfigOption',
        ),
        migrations.AddField(
            model_name='farmerdata',
            name='crop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.croptype'),
        ),
    ]
